"""Validation for countries/*.json.

Run by build.py before anything is rendered, so a malformed country fails the
build instead of quietly shipping. Also runnable on its own:

    python site/validate.py            # check every country
    python site/validate.py ireland    # check one
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COUNTRIES = ROOT / "countries"

# Must stay in step with CATEGORY_COLORS in the renderer.
VALID_CATEGORIES = {
    "Military", "Political", "Economic", "Indigenous", "Aboriginal",
    "Foreign Relations", "Cultural", "Social", "Scientific", "Religious",
}

REQUIRED_COUNTRY = {"name", "center_lat", "center_lng", "default_zoom"}
REQUIRED_ERA = {
    "name", "short_name", "sort_order", "year_start",
    "year_end", "date_label", "width_pct", "color",
}
REQUIRED_EVENT = {"id", "era_name", "sort_year", "display_date", "title"}

# The palette has exactly ten colours and the legend is laid out for ten. An
# eleventh era silently reuses a colour; nine looks unfinished beside the others.
ERA_COUNT = 10

# is_major controls dot size, so the band is about legibility: if most dots are
# emphasised, none of them are. Warn outside the target, fail outside the outer
# bound. Both were prose in countries/README.md until 20/08/2026 and drifted -
# Taiwan sat at 13% and Norway, Italy and Mexico each came in over 55% on a
# first pass.
MAJOR_TARGET = (0.35, 0.45)
MAJOR_HARD = (0.25, 0.55)

# En and em dashes are banned in anything rendered (house rule). `source` is
# exempt and is checked separately - a slug must match the article title, and
# some titles genuinely contain an en dash.
DASHES = ("–", "—")

# A title that trails off, ends on a colon, or stops mid-number is always a
# defect. Taiwan had 62 of them because its titles were generated by splitting
# each description on ".", which cut at decimal points too: "Taiwan receives $1"
# was really $1.5 billion. Data fixed 20/08/2026; this is here so an import
# cannot quietly reintroduce it.
TRUNCATED_TITLE = re.compile(r"(\.\.\.|…|:)\s*$")
CUT_NUMBER = re.compile(r"[$~(]\s*\d+\s*$")
RENDERED_EVENT_FIELDS = ("display_date", "title", "description")
RENDERED_ERA_FIELDS = ("name", "short_name", "date_label")

# A source is the Wikipedia article slug, not a URL - "Battle_of_Clontarf",
# never "https://en.wikipedia.org/wiki/Battle_of_Clontarf". The renderer builds
# the URL, so storing a full one would double it up.
#
# A slug must match the article title EXACTLY, so this is the one field where
# the no-dash house rule does not apply: "Egyptian-Hittite peace treaty" is not
# an article and "Egyptian–Hittite_peace_treaty" is. Diacritics likewise.
# It is a machine identifier, not rendered prose - the reader only ever sees the
# word "Wikipedia".
SOURCE_SLUG = re.compile(r"^[^\s%#?&=/]+$")


def validate(data: dict, label: str) -> tuple[list[str], list[str]]:
    """Check one country.

    Returns (errors, warnings). Errors fail the build - they mean the page
    would render wrongly or not at all. Warnings are reported and ignored,
    because some of them are legitimate editorial choices: precursor events are
    often placed in the era they belong to narratively rather than the one
    their date falls in (Iceland's pre-874 voyages sit in the Settlement Age;
    Taiwan's events about Koxinga's father sit in the Koxinga era).
    """
    errors: list[str] = []
    warnings: list[str] = []

    def err(msg: str) -> None:
        errors.append(f"{label}: {msg}")

    def warn(msg: str) -> None:
        warnings.append(f"{label}: {msg}")

    country = data.get("country") or {}
    eras = data.get("eras") or []
    events = data.get("events") or []

    for k in REQUIRED_COUNTRY - set(country):
        err(f"country is missing {k!r}")
    if not eras:
        err("no eras")
    if not events:
        err("no events")

    # --- eras ---
    for i, e in enumerate(eras):
        for k in REQUIRED_ERA - set(e):
            err(f"era[{i}] missing {k!r}")
        if e.get("year_start") is not None and e.get("year_end") is not None:
            if e["year_start"] > e["year_end"]:
                err(f"era {e.get('name')!r} has year_start after year_end")

    if eras and len(eras) != ERA_COUNT:
        err(f"{len(eras)} eras, expected {ERA_COUNT} - the palette has "
            f"{ERA_COUNT} colours and the legend is laid out for {ERA_COUNT}")

    for i, e in enumerate(eras):
        for f in RENDERED_ERA_FIELDS:
            v = e.get(f)
            if isinstance(v, str) and any(d in v for d in DASHES):
                err(f"era[{i}] {f} contains an en or em dash: {v!r}")

    total_width = sum(e.get("width_pct", 0) for e in eras)
    if round(total_width, 6) != 100:
        err(f"era width_pct sums to {total_width}, not 100")

    orders = [e.get("sort_order") for e in eras]
    if orders != sorted(orders):
        err("eras are not in sort_order order")
    if len(set(orders)) != len(orders):
        err("duplicate era sort_order values")

    era_names = {e.get("name") for e in eras}
    if len(era_names) != len(eras):
        err("duplicate era names")

    # --- events ---
    # The id is PERMANENT and lives in the data. It used to be the array index,
    # which meant moving or inserting one event silently renumbered every later
    # event and broke their /country/#event-N deep links. Never renumber; a new
    # event takes max(existing) + 1 wherever it sits in the order.
    ids = [ev.get("id") for ev in events if "id" in ev]
    for i, ev in zip(ids, [e for e in events if "id" in e]):
        if not isinstance(i, int) or isinstance(i, bool) or i < 0:
            err(f"event {ev.get('title', '?')!r} has a non-integer or negative id {i!r}")
    dupe_ids = {i for i in ids if ids.count(i) > 1}
    if dupe_ids:
        err(f"duplicate event ids: {sorted(dupe_ids)}")

    seen_titles = set()
    for i, ev in enumerate(events):
        where = f"event[{i}] {ev.get('title', '?')!r}"

        for k in REQUIRED_EVENT - set(ev):
            err(f"{where} missing {k!r}")
        if not str(ev.get("title", "")).strip():
            err(f"{where} has an empty title")

        # Era must match EXACTLY. Fuzzy matching used to paper over this and it
        # meant an era rename could silently move events - see the Taiwan
        # normalisation in TODO.md.
        if ev.get("era_name") not in era_names:
            err(f"{where} era_name {ev.get('era_name')!r} matches no era")
        else:
            era = next(e for e in eras if e["name"] == ev["era_name"])
            y = ev.get("sort_year")
            # sort_year carries a fractional part to order events within a year
            # (1944.4 is May 1944), so compare on the whole year - an era ending
            # in 1944 contains every month of 1944.
            if y is not None and not (era["year_start"] <= int(y // 1) <= era["year_end"]):
                warn(
                    f"{where} sort_year {y} outside its era "
                    f"[{era['year_start']}, {era['year_end']}]"
                )

        for c in ev.get("categories") or []:
            if c not in VALID_CATEGORIES:
                err(f"{where} unknown category {c!r}")

        lat, lng = ev.get("lat"), ev.get("lng")
        if (lat is None) != (lng is None):
            err(f"{where} has only one of lat/lng")
        if lat is not None and not (-90 <= lat <= 90):
            err(f"{where} lat {lat} out of range")
        if lng is not None and not (-180 <= lng <= 180):
            err(f"{where} lng {lng} out of range")

        src = ev.get("source")
        if src is not None:
            if not isinstance(src, str) or not src.strip():
                err(f"{where} has an empty source")
            elif "://" in src or src.startswith("en.wikipedia"):
                err(f"{where} source {src!r} is a URL - store the article slug only")
            elif " " in src:
                err(f"{where} source {src!r} contains a space - use underscores")
            elif not SOURCE_SLUG.match(src):
                err(f"{where} source {src!r} is not a valid article slug")
        elif ev.get("is_major"):
            err(f"{where} is_major but has no source")

        title = ev.get("title")
        if isinstance(title, str):
            if TRUNCATED_TITLE.search(title):
                err(f"{where} title is truncated or ends on a colon")
            elif CUT_NUMBER.search(title):
                err(f"{where} title stops mid-number - the full figure is "
                    f"usually still in the description")
            elif title.count('"') % 2:
                # A title cut at its closing quote mark. Taiwan had two.
                err(f"{where} title has an unbalanced quote mark")

        for f in RENDERED_EVENT_FIELDS:
            v = ev.get(f)
            if isinstance(v, str) and any(d in v for d in DASHES):
                err(f"{where} {f} contains an en or em dash")

        t = ev.get("title")
        if t in seen_titles:
            err(f"{where} duplicate title")
        seen_titles.add(t)

    if events and [e.get("sort_year") for e in events] != sorted(
        e.get("sort_year") for e in events
    ):
        warn("events are not sorted by sort_year")

    # Two-tailed on purpose. The old check only fired above 55%, so it never
    # caught the other end, and Taiwan sat at 13% unnoticed for months.
    majors = sum(1 for e in events if e.get("is_major"))
    if events:
        ratio = majors / len(events)
        lo, hi = MAJOR_TARGET
        hard_lo, hard_hi = MAJOR_HARD
        if not (hard_lo <= ratio <= hard_hi):
            err(f"{majors}/{len(events)} flagged is_major ({ratio:.0%}) - outside "
                f"{hard_lo:.0%}-{hard_hi:.0%}, aim for {lo:.0%}-{hi:.0%}")
        elif not (lo <= ratio <= hi):
            warn(f"{majors}/{len(events)} flagged is_major ({ratio:.0%}) - "
                 f"aim for {lo:.0%}-{hi:.0%}")

    return errors, warnings


def validate_file(path: Path) -> tuple[list[str], list[str]]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return ([f"{path.name}: invalid JSON - {exc}"], [])
    return validate(data, path.stem)


def validate_all(only: str | None = None) -> tuple[list[str], list[str]]:
    files = sorted(COUNTRIES.glob("*.json"))
    if only:
        files = [f for f in files if f.stem == only]
    errors, warnings = [], []
    for f in files:
        e, w = validate_file(f)
        errors.extend(e)
        warnings.extend(w)
    return errors, warnings


if __name__ == "__main__":
    only = sys.argv[1].lower() if len(sys.argv) > 1 else None
    errors, warnings = validate_all(only)
    for w in warnings:
        print("  warn:", w)
    if errors:
        print(f"\n{len(errors)} error(s):\n")
        for e in errors:
            print("  -", e)
        sys.exit(1)
    n = 1 if only else len(list(COUNTRIES.glob("*.json")))
    print(f"\n{n} country file(s) valid ({len(warnings)} warning(s)).")
